// <auto-generated />
using System;
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = 1, FirstName = "Frank",  LastName = "Herbert" },
                        new { Id = 2, FirstName = "Ursula", LastName = "Le Guin" },
                        new { Id = 3, FirstName = "Isaac",  LastName = "Asimov"  });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId").HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear").HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("AuthorId");
                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, AuthorId = 1, Isbn = "978-0-441-17271-9", PublishedYear = 1965, Title = "Dune" },
                        new { Id = 2, AuthorId = 1, Isbn = "978-0-441-17269-6", PublishedYear = 1969, Title = "Dune Messiah" },
                        new { Id = 3, AuthorId = 2, Isbn = "978-0-441-47812-5", PublishedYear = 1969, Title = "The Left Hand of Darkness" },
                        new { Id = 4, AuthorId = 2, Isbn = "978-0-061-05488-9", PublishedYear = 1974, Title = "The Dispossessed" },
                        new { Id = 5, AuthorId = 3, Isbn = "978-0-553-29335-7", PublishedYear = 1951, Title = "Foundation" });
                });

            modelBuilder.Entity("LibraryApp.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId").HasColumnType("INTEGER");
                    b.Property<string>("BorrowerName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<DateTime>("BorrowedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("ReturnedAt").HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("BookId");
                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryApp.Models.Borrowing", b =>
                {
                    b.HasOne("LibraryApp.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                { b.Navigation("Books"); });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                { b.Navigation("Borrowings"); });
#pragma warning restore 612, 618
        }
    }
}
